import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { ViewTransitions } from 'next-view-transitions'


const inter = Inter({weight: ["400", "500", "600", "700", "800", "900"]});

export const metadata: Metadata = {
  title: "Saurabh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
     <html lang="en" suppressHydrationWarning>
      <body 
        className={`${inter.className}  antialiased bg-background dark:bg-background`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Navbar/>
        {children}
        </ThemeProvider>
      </body>
    </html>
    </ViewTransitions>
  );
}
